In [21]:
import cv2
import numpy as np

# Load the image
img = cv2.imread("Final_Hackathon_Data/Bad_Images[75 <Accuracy < 85 ]/PMI-472031-7_dot__std.jpg")

# Convert the image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply the Canny edge detection algorithm
edges = cv2.Canny(gray, 50, 150)

# Find the contours in the image
contours, hierarchy = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Draw the contours on the original image
cv2.drawContours(img, contours, -1, (0, 255, 0), 3)

cv2.imwrite("output.jpg",img)


True

In [2]:
image_file = 'Final_Hackathon_Data/Bad_Images[75 <Accuracy < 85 ]/PMI-472031-7_dot__std.jpg'

In [25]:
import cv2
import numpy as np

# Load the input image
img = cv2.imread(image_file, cv2.IMREAD_GRAYSCALE)

# Threshold the image to create a binary image
threshold, img_bin = cv2.threshold(img, 128, 255, cv2.THRESH_BINARY)

# Perform connected component analysis
output = cv2.connectedComponentsWithStats(img_bin, 4, cv2.CV_32S)

# Get the number of connected components and the labels map
num_components = output[0]
labels = output[1]

# Create a color map for the connected components
colors = np.random.randint(0, 255, size=(num_components, 3), dtype="uint8")

# Loop over the connected components
for i in range(1, num_components):
    # Get the pixels with the same label
    component = np.zeros(img.shape, dtype="uint8")
    component[labels == i] = 255

    # Randomly color the component
    color = tuple(colors[i].tolist())
    colored_component = cv2.merge([component, component, component])
    # colored_component = cv2.cvtColor(colored_component, cv2.COLOR_BGR2GRAY)
    # colored_component = cv2.cvtColor(colored_component, cv2.COLOR_GRAY2BGR)
    colored_component[component == 255] = (0,0,255)

    # Show the component
    cv2.imwrite("Component {}.png".format(i), colored_component)
    break



In [23]:
type(color)

tuple

In [17]:
component = cv2.imread('Component 1.png')
img_reshaped = component.reshape(-1, 3)

# Find the unique RGB values
unique_pixels, counts = np.unique(img_reshaped, axis=0, return_counts=True)

# Print the unique RGB values
print(unique_pixels)

[[  0   0   0]
 [235  99 222]]


In [40]:
image_file = 'Final_Hackathon_Data/Bad_Images[75 <Accuracy < 85 ]/PMI-472031-7_dot__std.jpg'

In [42]:
import cv2
import numpy as np

# Load the image
img = cv2.imread(image_file)

# Convert the image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imwrite("gray_temp.jpg",gray)
# Apply Gaussian blur
blur = cv2.GaussianBlur(gray, (5, 5), 0)

# Detect edges using Canny
edges = cv2.Canny(blur, 50, 150)
cv2.imwrite("edge_temp.jpg",edges)

# Detect circles using HoughCircles
circles = cv2.HoughCircles(edges, cv2.HOUGH_GRADIENT, 1, 20, param1=50, param2=30, minRadius=8, maxRadius=50)

# # Filter circles based on the desired radius
# desired_radius = 20
# filtered_circles = []
# for i in circles[0, :]:
#     if i[2] == desired_radius:
#         filtered_circles.append(i)

# # Draw the filtered circles onto the original image
# for i in circles:
#     cv2.circle(img, (i[0], i[1]), i[2], (255, 255, 255), 2)
#     cv2.circle(img, (i[0], i[1]), 2, (255, 255, 255), 3)

# cv2.imwrite("noise.jpg",img)


In [55]:
edges

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [56]:
template = np.zeros((2,2),np.uint8)
template

array([[0, 0],
       [0, 0]], dtype=uint8)

In [57]:
eroded_image = cv2.erode(edges, template, iterations=1)

In [59]:
cv2.imwrite("erode.jpg",eroded_image)

True

In [24]:
edge_input = cv2.imwrite("edges.jpg",edges)

################################

In [2]:
import cv2
import numpy as np
test_input = cv2.imread("edges.jpg")
gray = cv2.cvtColor(test_input, cv2.COLOR_BGR2GRAY)

In [14]:
small_gray = gray[0:10,0:10]
small_gray.shape

(10, 10)

In [15]:
circles = cv2.HoughCircles(small_gray, cv2.HOUGH_GRADIENT, 1, 1, param1=1, param2=3, minRadius=10, maxRadius=50)

In [16]:
circles

In [9]:
import cv2
import numpy as np
image = np.array(edges, dtype=np.uint8)

In [12]:
cv_image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
type(cv_image)

error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 3


In [4]:
circles = cv2.HoughCircles(cv_image, cv2.HOUGH_GRADIENT, 1, 1, param1=1, param2=3, minRadius=2, maxRadius=50)

error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/hough.cpp:2269: error: (-215:Assertion failed) !_image.empty() && _image.type() == CV_8UC1 && (_image.isMat() || _image.isUMat()) in function 'HoughCircles'


In [19]:
image = np.zeros((500, 500), dtype=np.uint8)
edges

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [60]:
import cv2

In [61]:
net = cv2.dnn.readNet('frozen_east_text_detection.pb')

In [62]:
image = cv2.imread('Final_Hackathon_Data/Good_Images [85 < Accuracy < 95]/image._std.jpg')

In [67]:
(inpHeight,inpWidth) =  image.shape[0:2]

In [68]:
blob = cv2.dnn.blobFromImage(image, 1.0, (inpWidth, inpHeight), (123.68, 116.78, 103.94), True, False)


In [69]:
outputLayers = []
outputLayers.append("feature_fusion/Conv_7/Sigmoid")
outputLayers.append("feature_fusion/concat_3")

In [70]:
net.setInput(blob)
output = net.forward(outputLayers)
scores = output[0]
geometry = output[1]

[ERROR:0@11489.797] global net_impl.cpp:1161 getLayerShapesRecursively OPENCV/DNN: [Concat]:(feature_fusion/concat): getMemoryShapes() throws exception. inputs=2 outputs=1/1 blobs=0
[ERROR:0@11489.798] global net_impl.cpp:1167 getLayerShapesRecursively     input[0] = [ 1 2048 28 40 ]
[ERROR:0@11489.798] global net_impl.cpp:1167 getLayerShapesRecursively     input[1] = [ 1 512 27 40 ]
[ERROR:0@11489.798] global net_impl.cpp:1171 getLayerShapesRecursively     output[0] = [ 1 2048 28 40 ]
[ERROR:0@11489.798] global net_impl.cpp:1177 getLayerShapesRecursively Exception message: OpenCV(4.7.0) /io/opencv/modules/dnn/src/layers/concat_layer.cpp:109: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'getMemoryShapes'



error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/layers/concat_layer.cpp:109: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'getMemoryShapes'


#####################

In [357]:
import os
import cv2
import numpy as np
import random

In [358]:
level = 'bad'
blur_level = 2
noise_level= 0.5

In [359]:
blur_level = blur_level * 5
noise_level = noise_level
spot_level = 0.3

In [360]:
os.system(f'cd ./output/ && mkdir {level}')
os.system(f'cd ./output/{level}/ && mkdir _noise _blur _spot')

0

In [401]:
def blur_image(image):
    # Create a Gaussian blur kernel with a random kernel size
    # kernel_size = random.randint(1, 21)
    # if kernel_size %2 ==0:
    #     kernel_size += 1
    kernel = (5, 5)

    # Apply Gaussian blur to the image
    return cv2.GaussianBlur(image, kernel, blur_level)

def add_noise(image):
    # Create a noisy image by adding random values to the original image
    row, col, _ = image.shape
    mean = 0
    var = random.uniform(0, 50)
    sigma = var**(noise_level)*(row*col//10000)
    noise = np.random.normal(mean, sigma, (row, col, 3))
    noisy_image = image + noise

    # Clipping the image to keep its values between 0 and 255
    noisy_image = np.clip(noisy_image, 0, 255).astype(np.uint8)

    return noisy_image

def add_black_spot(image):
    # Add a black spot to the image by replacing a random rectangular region with zeros
    row, col, _ = image.shape
    print(image.shape)
    spot_width = random.randint(5, 10)
    spot_height = random.randint(5, 10)
    spot_density = int(row*col*0.00001)
    for _ in range(spot_density):
        x = random.randint(0, row - spot_height)
        y = random.randint(0, col - spot_width)
        image[x:x+spot_height, y:y+spot_width] = 0

    return image

def degrade_image(image,filename,level):
    # Degrade the image by applying a random combination of the blur, noise and black spot functions
    operations = {blur_image:"_blur", add_noise:"_noise", add_black_spot:"_spot"}
    for operation in operations:
        result = operation(image)
        cv2.imwrite(f'./output/{level}/{operations[operation]}/'+filename+operations[operation]+".jpg",result)

In [402]:
for filename in os.listdir('DIBCOdataset'):
    image = cv2.imread('DIBCOdataset/'+filename)
    filename = filename.split('.')[0]
    print(filename)
    degrade_image(image,filename,level)
    

image05
(1069, 1315, 3)
image03
(357, 1849, 3)
image02
(768, 1320, 3)
image07
(479, 1661, 3)
image06
(564, 600, 3)
image04
(363, 1203, 3)
image08
(323, 859, 3)


In [268]:
1069 * 1315

1405735